# Generated by Django 2.1.7 on 2019-03-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_enterprise', models.CharField(max_length=50)),
                ('name_of_enterpreneur', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
    ]
