# Generated by Django 2.1.7 on 2019-04-10 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigstartup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='id',
        ),
        migrations.AddField(
            model_name='startup',
            name='Signature',
            field=models.FileField(default='#', upload_to=''),
        ),
        migrations.AddField(
            model_name='startup',
            name='address',
            field=models.TextField(default='', verbose_name='permanent address'),
        ),
        migrations.AddField(
            model_name='startup',
            name='attachment_of_bplan',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='startup',
            name='benefic',
            field=models.TextField(default='', verbose_name='Who will benefit from your product/Service'),
        ),
        migrations.AddField(
            model_name='startup',
            name='current_space',
            field=models.TextField(blank=True, default='', verbose_name='Are you currently occupying a space ? If yes give details such as area, location and monthly cost'),
        ),
        migrations.AddField(
            model_name='startup',
            name='descr',
            field=models.TextField(default='', verbose_name='Description of your business products/services'),
        ),
        migrations.AddField(
            model_name='startup',
            name='descr_bplan',
            field=models.TextField(default='', verbose_name='Description of your b plan and attach a copy of the same'),
        ),
        migrations.AddField(
            model_name='startup',
            name='dob',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='startup',
            name='education',
            field=models.CharField(default='#', max_length=20),
        ),
        migrations.AddField(
            model_name='startup',
            name='employee_space',
            field=models.TextField(default='', verbose_name='Mention number of employees occupying the space'),
        ),
        migrations.AddField(
            model_name='startup',
            name='if_select',
            field=models.TextField(default='', verbose_name='If selected , when will you start the incubation facility ?'),
        ),
        migrations.AddField(
            model_name='startup',
            name='impact',
            field=models.CharField(choices=[('d', 'Direct'), ('i', 'Indirect')], default='', max_length=30, verbose_name='type of impact on social sector'),
        ),
        migrations.AddField(
            model_name='startup',
            name='infra_resource',
            field=models.TextField(default='', verbose_name='What all infrastructural resources you require ? Mention them clearly'),
        ),
        migrations.AddField(
            model_name='startup',
            name='is_your_enterprise',
            field=models.CharField(choices=[('r', 'Registered'), ('n', 'Not Registered')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='startup',
            name='mention',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Mention your sector if not mentioned above'),
        ),
        migrations.AddField(
            model_name='startup',
            name='name_of_mentor',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='startup',
            name='nu_mentor',
            field=models.BooleanField(default=False, verbose_name='Have a mentor from NU ?'),
        ),
        migrations.AddField(
            model_name='startup',
            name='organization_type',
            field=models.CharField(choices=[('n', 'Not for Profit Organization'), ('p', 'For Profit Organization')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='startup',
            name='other_de',
            field=models.TextField(blank=True, default='', verbose_name='Any other details you want to give which will help evaluating your proposal ? '),
        ),
        migrations.AddField(
            model_name='startup',
            name='pro_req',
            field=models.TextField(blank=True, verbose_name='Mention requirements of professional services/support if needed'),
        ),
        migrations.AddField(
            model_name='startup',
            name='sector',
            field=models.CharField(choices=[('ai', 'Information, Communication and Entertainment'), ('bi', 'Food, Agriculture and allied sectors'), ('ci', 'Augmented Reality , Big data and analytics , Image Processing and Recognition ,Cloud computing, Cyber Security'), ('di', 'Renewable energy sources , Green Technology'), ('ei', 'Bio Informatics'), ('fi', 'Financial Technology, NPD , Services'), ('gi', 'Other Contemporary area')], default='', max_length=300, verbose_name='sector for your enterprise'),
        ),
        migrations.AddField(
            model_name='startup',
            name='sourc_fund',
            field=models.TextField(blank=True, default='', verbose_name='Specify sources of funds'),
        ),
        migrations.AddField(
            model_name='startup',
            name='special_req',
            field=models.TextField(blank=True, default='', verbose_name='Mention any special requirement'),
        ),
        migrations.AddField(
            model_name='startup',
            name='stp_benefit',
            field=models.TextField(default='', verbose_name='How will your startup be benefitted from incubating at NU'),
        ),
        migrations.AddField(
            model_name='startup',
            name='website',
            field=models.CharField(blank=True, default='', max_length=300, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='nationality',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='startup',
            name='phone_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
