# Generated by Django 2.1.7 on 2019-04-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nustartup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nustartup',
            name='team',
            field=models.TextField(default='insert'),
        ),
    ]
